apiVersion: v1
kind: Service
metadata: 
  name: nginx-LoadBalancer
spec:
  type: {{ .Values.service.type }}
  selector:
    project: beta
  ports:
    - protocol: TCP  
      port: {{ .Values.service.servicePort }}
      targetPort: 80
      nodePort: 30007
  
